parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Shared\Domain\Bus\Command\CommandHandlerInterface:
            tags: [ messenger.message_handler ]

        App\Shared\Domain\Bus\Event\EventHandlerInterface:
            tags: [ messenger.message_handler ]

    # context
    App\Catalog\:
        resource: '../../src/Catalog/'

    # controllers
    App\Catalog\Infrastructure\Http\:
        resource: '../../src/Catalog/Infrastructure/Http/'
        tags: ['controller.service_arguments']

    App\Catalog\Infrastructure\Normalizer\:
        resource: '../../src/Catalog/Infrastructure/Normalizer/*'
        tags: [ serializer.normalizer ]

    # repositories
    App\Catalog\Domain\Product\ProductRepository: '@App\Catalog\Infrastructure\Doctrine\DoctrineProductRepository'
    App\Catalog\Domain\Category\CategoryRepository: '@App\Catalog\Infrastructure\Doctrine\DoctrineCategoryRepository'
    App\Catalog\Domain\Brand\BrandRepository: '@App\Catalog\Infrastructure\Doctrine\DoctrineBrandRepository'
    App\Catalog\Domain\Seller\SellerRepository: '@App\Catalog\Infrastructure\Doctrine\DoctrineSellerRepository'
