catalog_product_find:
    path: /catalog/product/{reference}
    methods: [GET]
    controller: App\Catalog\Infrastructure\Http\Product\FindProductController
    stateless: true

catalog_product_delete:
    path: /catalog/product/{reference}
    methods: [DELETE]
    controller: App\Catalog\Infrastructure\Http\Product\DeleteProductController
    stateless: true

catalog_product_update:
    path: /catalog/product/{reference}
    methods: [PUT]
    controller: App\Catalog\Infrastructure\Http\Product\UpdateProductController
    stateless: true

catalog_product_create:
    path: /catalog/product
    methods: [POST]
    controller: App\Catalog\Infrastructure\Http\Product\CreateProductController
    stateless: true

catalog_product_search:
    path: /catalog/search
    methods: [GET]
    controller: App\Catalog\Infrastructure\Http\Product\SearchProductController
    stateless: true

catalog_picture_stream:
    path: /picture/{id}/stream
    methods: [GET]
    controller: App\Catalog\Infrastructure\Http\Picture\StreamPictureController
    stateless: true
